version: '3'
services:
    mysqldb:
        build:
            context: .
            dockerfile: ./Dockerfile_MySQL
            args:
                MYSQL_DATABASE: 'DB'
                #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                MYSQL_ROOT_PASSWORD: password
          #      DB_PORT: 3306
          #      MYSQL_READ_ONLY_USER: "report"
        ports:
          - "3306:3306"
        expose:
          - '3306'  
        environment:
# I ran into peculiar trouble trying to secure password with envvar       
          #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: DB  
        container_name: mysqldb       
        #MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
        # secrets:
        #   - mysql_root_password
        #   - mysql_user_password
        healthcheck:
          test: ["CMD-SHELL", "mysql -h mysqldb -u  root -p$$MYSQL_ROOT_PASSWORD" ]
          interval: 30s
          timeout: 20s
          retries: 3
                
    webserver:
        build:
            context: .
            dockerfile: ./Dockerfile_NGINX
            args:
                DBNAME: 'DB'
                MYSQLUSER: "report"
                OUTFILE: somefile
                #DBHOST: mysqldb
                DBHOST: host.docker.internal
                #DBHOST: 172.19.244.87
          
        depends_on: 
          mysqldb:
              condition: service_healthy        
        ports:
          - "9980:80"        
        expose:
          - '9980'
        # secrets:
        #   - mysql_user_password
  
# not going to  use
# secrets:
#   mysql_root_password:
#     #external: true
#     file: mysql_root_password
#   mysql_user_password:
#     #external: true
#     file: mysql_user_password

          

